shallow_clone: true

os:
  - Visual Studio 2015 Update 2

build:
  verbosity: detailed

configuration:
  - Debug

environment:
  matrix:
    - TESTS_ONLY: true
    - EXAMPLES_ONLY: true

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\hello-cdep

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - cmake .. --build
